# Generated by Django 4.2.30 on 2026-07-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_aireportschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireportschedule',
            name='kind',
            field=models.CharField(choices=[('activity', 'Activity report - what happened'), ('open_tickets', 'Open-ticket review - what could be done'), ('tech_productivity', 'Technician Productivity Analysis - how each tech is doing')], default='activity', max_length=20),
        ),
    ]
