# Generated by Django 4.2.30 on 2026-08-04 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0063_agent_ai_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0103_coresettings_ai_sales_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISpendEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('turn_index', models.PositiveIntegerField(default=0)),
                ('surface', models.CharField(choices=[('device_chat', 'Device chat / pichat'), ('decision_chat', 'Ticket (AI-decision) chat'), ('unattended', 'Unattended run (scheduled task / bulk / action)'), ('verifier', 'Alert verifier'), ('other', 'Other')], default='device_chat', max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('model_id', models.CharField(db_index=True, max_length=255)),
                ('actor_username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('agent_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('site', models.CharField(blank=True, default='', max_length=255)),
                ('ticket_ref', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveBigIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveBigIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('cost_input', models.DecimalField(decimal_places=10, default=0, max_digits=16)),
                ('cost_output', models.DecimalField(decimal_places=10, default=0, max_digits=16)),
                ('cost_cache_read', models.DecimalField(decimal_places=10, default=0, max_digits=16)),
                ('cost_cache_write', models.DecimalField(decimal_places=10, default=0, max_digits=16)),
                ('cost_total', models.DecimalField(decimal_places=10, default=0, max_digits=16)),
                ('priced', models.BooleanField(default=True)),
                ('context_tokens', models.PositiveBigIntegerField(default=0)),
                ('was_model_switch', models.BooleanField(default=False)),
                ('at', models.DateTimeField(db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_spend_entries', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_spend_entries', to='agents.agent')),
            ],
            options={
                'indexes': [models.Index(fields=['at', 'client'], name='core_aispen_at_157b64_idx'), models.Index(fields=['at', 'actor_username'], name='core_aispen_at_29f690_idx'), models.Index(fields=['at', 'model_id'], name='core_aispen_at_87f5cc_idx'), models.Index(fields=['at', 'surface'], name='core_aispen_at_e1cb78_idx')],
                'unique_together': {('session_id', 'turn_index')},
            },
        ),
    ]
