# Generated by Django 4.2.30 on 2026-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_ai_spend_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireportschedule',
            name='kind',
            field=models.CharField(choices=[('activity', 'Activity report - what happened'), ('open_tickets', 'Open-ticket review - what could be done'), ('tech_productivity', 'Technician Productivity Analysis - how each tech is doing'), ('ai_spend', 'AI Spend - what the AI cost, from the spend ledger')], default='activity', max_length=20),
        ),
    ]
