# Generated by Django 4.2.30 on 2026-08-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_ai_spend_report_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_erp_allowed_origins',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_erp_integration_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_erp_ws_base',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
