# Generated by Django 4.2.30 on 2026-08-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_coresettings_ai_erp_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aispendentry',
            name='surface',
            field=models.CharField(choices=[('device_chat', 'Device chat / pichat'), ('decision_chat', 'Ticket (AI-decision) chat'), ('unattended', 'Unattended run (scheduled task / bulk / action)'), ('verifier', 'Alert verifier'), ('odoo', 'Odoo AI panel (CRM / quotations)'), ('other', 'Other')], default='device_chat', max_length=20),
        ),
    ]
