# Generated by Django 4.2.30 on 2026-09-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_aiagentgroupmember_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aispendentry',
            name='surface',
            field=models.CharField(choices=[('device_chat', 'Device chat / pichat'), ('decision_chat', 'Ticket (AI-decision) chat'), ('unattended', 'Unattended run (scheduled task / bulk / action)'), ('verifier', 'Alert verifier'), ('report', 'Scheduled report (compile)'), ('analyze', 'Scheduled report (executive summary)'), ('triage', 'Ticket triage'), ('resolve', 'Ticket auto-resolve'), ('mining', 'Procedure mining'), ('assist', 'Settings assistant (prompt / code helpers)'), ('group', 'Agent-group specialist (delegated inside a chat)'), ('odoo', 'Odoo AI panel (CRM / quotations)'), ('other', 'Other')], default='device_chat', max_length=20),
        ),
    ]
