# Generated by Django 4.2.30 on 2026-09-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_alter_aispendentry_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='aispendentry',
            name='backfilled',
            field=models.BooleanField(default=False),
        ),
    ]
