# Generated by Django 4.2.30 on 2026-09-14 16:23

from django.db import migrations, models


def pin_existing_tasks_to_utc(apps, schema_editor):
    """Existing tasks keep firing at exactly the same moment as before.

    Before this field, `run_time` was localised with Django's TIME_ZONE - UTC on this
    install - so "daily 03:00" meant 03:00 UTC. The new default (blank = the device's own
    timezone) is the right behaviour for tasks authored from now on, but applying it
    retroactively would silently move every existing maintenance window by hours, on
    machines whose customers agreed to the old slot. So the old meaning is written down
    explicitly rather than changed.
    """
    from django.conf import settings

    apps.get_model("core", "AITask").objects.update(
        schedule_timezone=settings.TIME_ZONE or "UTC"
    )


def unpin(apps, schema_editor):
    apps.get_model("core", "AITask").objects.update(schedule_timezone="")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_aispendentry_backfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='schedule_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(pin_existing_tasks_to_utc, unpin),
    ]
