# Generated by Django 4.2.30 on 2026-09-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_aitask_schedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITicketAutomationSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('proposed', 'Proposed by the daily report - awaiting approval'), ('approved', 'Approved - live'), ('rejected', 'Rejected'), ('retired', 'Retired')], default='proposed', max_length=12)),
                ('enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('advise', 'Advise - reply to the customer; no device access at all'), ('device_readonly', 'Investigate - read-only probes on devices, then advise'), ('device_fix', 'Fix - run the attached remediation script (needs a script)')], default='advise', max_length=20)),
                ('match', models.JSONField(blank=True, default=dict)),
                ('kb_article_ids', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField(blank=True, default='')),
                ('all_clients', models.BooleanField(default=False)),
                ('clients', models.JSONField(blank=True, default=list)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('baseline_minutes', models.FloatField(blank=True, null=True)),
                ('approve_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('reject_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('proposed_by_report', models.DateTimeField(blank=True, null=True)),
                ('proposal_reason', models.TextField(blank=True, default='')),
                ('proposal_tickets', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=150)),
                ('tickets_matched', models.PositiveIntegerField(default=0)),
                ('tickets_worked', models.PositiveIntegerField(default=0)),
                ('tickets_deduped', models.PositiveIntegerField(default=0)),
                ('last_worked', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='company_specifics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absorbed', to='core.aiprocedure'),
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiprocedure',
            name='score_reason',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='aireportschedule',
            name='kind',
            field=models.CharField(choices=[('activity', 'Activity report - what happened'), ('open_tickets', 'Open-ticket review - what could be done'), ('tech_productivity', 'Technician Productivity Analysis - how each tech is doing'), ('ai_spend', 'AI Spend - what the AI cost, from the spend ledger'), ('autowork_readiness', 'AI Auto-work Readiness - would it work each ticket alone'), ('automation_subjects', 'Ticket Automation Subjects - what to automate next')], default='activity', max_length=32),
        ),
        migrations.AlterField(
            model_name='aispendentry',
            name='surface',
            field=models.CharField(choices=[('device_chat', 'Device chat / pichat'), ('decision_chat', 'Ticket (AI-decision) chat'), ('unattended', 'Unattended run (scheduled task / bulk / action)'), ('verifier', 'Alert verifier'), ('report', 'Scheduled report (compile)'), ('analyze', 'Scheduled report (executive summary)'), ('triage', 'Ticket triage'), ('resolve', 'Ticket auto-resolve'), ('mining', 'Procedure mining'), ('assist', 'Settings assistant (prompt / code helpers)'), ('group', 'Agent-group specialist (delegated inside a chat)'), ('autowork', 'Ticket worked automatically under an automation subject'), ('odoo', 'Odoo AI panel (CRM / quotations)'), ('other', 'Other')], default='device_chat', max_length=20),
        ),
        migrations.CreateModel(
            name='AITicketWorkClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('ticket_ref', models.CharField(db_index=True, max_length=100)),
                ('worker', models.CharField(blank=True, default='', max_length=120)),
                ('what', models.CharField(blank=True, default='', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, default='', max_length=40)),
                ('duplicates', models.JSONField(blank=True, default=list)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aiticketautomationsubject')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.AddField(
            model_name='aiticketautomationsubject',
            name='procedures',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='core.aiprocedure'),
        ),
        migrations.AddConstraint(
            model_name='aiticketworkclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('fingerprint',), name='one_active_claim_per_fingerprint'),
        ),
    ]
