# Generated by Django 4.2.30 on 2026-09-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_automation_subjects_and_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_procedure_auto_approve_score',
            field=models.PositiveSmallIntegerField(default=95),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_procedure_auto_approve_seen',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
