# Generated by Django 4.2.30 on 2026-09-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_procedure_auto_approve_gates'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_chat_detach_grace_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
