# Generated by Django 4.2.30 on 2026-09-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_chat_detach_grace'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidecisionrequest',
            name='subject_kind',
            field=models.CharField(default='helpdesk', max_length=20),
        ),
        migrations.AddField(
            model_name='aidecisionrequest',
            name='subject_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_discovery_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
