# Generated by Django 4.2.30 on 2026-09-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_decision_subject_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketautomationsubject',
            name='fix_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiticketautomationsubject',
            name='fix_cooldown_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='aiticketautomationsubject',
            name='fixes_applied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiticketautomationsubject',
            name='last_fix_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
