# Generated by Django 4.2.30 on 2026-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_subject_fix_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketautomationsubject',
            name='fix_target',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
