# Generated by Django 4.2.30 on 2026-09-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_subject_fix_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='ai_ticket_poll_minutes',
            field=models.IntegerField(default=10),
        ),
    ]
