# Generated by Django 4.2.30 on 2026-09-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_ai_ticket_poll_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketstate',
            name='duplicate_of',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aiticketstate',
            name='held_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
