# Generated by Django 4.2.30 on 2026-09-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_spend_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
