# Generated by Django 4.2.30 on 2026-09-27 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0128_aiprovider_native_provider_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aispendentry',
            name='surface',
            field=models.CharField(choices=[('device_chat', 'Device chat / pichat'), ('decision_chat', 'Ticket (AI-decision) chat'), ('unattended', 'Unattended run (scheduled task / bulk / action)'), ('verifier', 'Alert verifier'), ('report', 'Scheduled report (compile)'), ('analyze', 'Scheduled report (executive summary)'), ('triage', 'Ticket triage'), ('resolve', 'Ticket auto-resolve'), ('mining', 'Procedure mining'), ('assist', 'Settings assistant (prompt / code helpers)'), ('group', 'Agent-group specialist (delegated inside a chat)'), ('autowork', 'Ticket worked automatically under an automation subject'), ('odoo', 'Odoo AI panel (CRM / quotations)'), ('relay', 'pi relay (remote pi client)'), ('other', 'Other')], default='device_chat', max_length=20),
        ),
        migrations.CreateModel(
            name='AIRelayKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text="e.g. 'Sean laptop'", max_length=100)),
                ('key_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('secret_hash', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.CharField(blank=True, default='', max_length=150)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.CharField(blank=True, default='', max_length=64)),
                ('daily_budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allowed_ips', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_keys', to='core.aiagentgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_relay_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
