# Generated by Django 4.2.30 on 2026-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_ai_relay_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='airelaykey',
            name='install_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airelaykey',
            name='install_sent_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='airelaykey',
            name='install_sent_to',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='airelaykey',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
