# Generated by Django 4.2.30 on 2026-09-27 12:20

from django.db import migrations, models


def set_preferred_group(apps, schema_editor):
    """Default the preferred group to the IT group (owner, 2026-09-27): triage and autowork
    then run on IT's orchestrator instead of the starred default model."""
    CoreSettings = apps.get_model("core", "CoreSettings")
    AIAgentGroup = apps.get_model("core", "AIAgentGroup")
    group = AIAgentGroup.objects.filter(slug="it", enabled=True).first() or AIAgentGroup.objects.filter(enabled=True).order_by("id").first()
    if not group:
        return
    for core in CoreSettings.objects.all():
        core.ai_preferred_agent_group_id = group.id
        core.save(update_fields=["ai_preferred_agent_group"])


def clear_preferred_group(apps, schema_editor):
    CoreSettings = apps.get_model("core", "CoreSettings")
    for core in CoreSettings.objects.all():
        core.ai_preferred_agent_group_id = None
        core.save(update_fields=["ai_preferred_agent_group"])
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_relay_key_multi_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketautomationsubject',
            name='agent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autowork_subjects', to='core.aiagentgroup'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='ai_preferred_agent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_settings', to='core.aiagentgroup'),
        ),
        migrations.RunPython(set_preferred_group, clear_preferred_group),
    ]
