# Generated by Django 4.2.30 on 2026-09-27 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0132_headless_agent_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISessionCapability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_kind', models.CharField(choices=[('ticket', 'One ticket'), ('device', 'One device'), ('all', 'Everywhere (standing)')], default='ticket', max_length=10)),
                ('scope_ref', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('caps', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('granted_by', models.CharField(blank=True, default='', max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.CharField(blank=True, default='', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_session_caps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'scope_kind', 'scope_ref'], name='core_aisess_user_id_04ddb3_idx')],
            },
        ),
    ]
