# Generated by Django 4.2.30 on 2026-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_ai_session_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentgroupmember',
            name='fallback_model_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aiagentgroupmember',
            name='fallback_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aiagentgroupmember',
            name='fallback_thinking_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
