# Generated by Django 4.2.30 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0134_member_fallback_model"),
    ]

    operations = [
        # Per-surface agent routing. Empty means "every surface inherits
        # ai_preferred_agent_group", which is exactly how the system behaved before this
        # field existed - so the migration changes no behaviour on its own.
        migrations.AddField(
            model_name="coresettings",
            name="ai_agent_routing",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
